### ISSUE TITLE
For 1180, add filters for minimum number of pages and minimum read percent

### ISSUE THREAD

**Issue by m60freeman** [microsoft/azure-sql-tips#63]
For "ROW or PAGE compression opportunities may exist":

- It does not seem worth the time to analyze small indexes, or to compress them once analyzed.
- It seems like compressing indexes with a high ratio of writes to reads is likely to cause more CPU overhead for the regular workload than it would be worth.

Adding parameters (@CompressionMinimumPageThreshold and  CompressionMinimumReadPercentage for those numbers and filtering on them seem like a good addition that would not significantly slow down the query, as the data is available in sys.partitions and sys.dm_db_index_usage_stats. 

Kalen Delaney has such code (although not parameterized) in her stored procedure [usp_estimate_data_compression_savings](https://www.sqlserverinternals.com/blog/2018/6/6/creating-my-own-spestimatedatacompressionsavings). Her procedure is much more comprehensive and takes much longer to run, but it seems easy enough to add another CTE and a WHERE clause to yours.

In one of my databases, her procedure produces 58 rows of compression recommendations (after 15 minutes of execution time), while yours produces 478 rows of XML output.

**Comment by dimitri-furman** [comment]
I had to take a closer look to refresh my memory. As it happens, we already consider the read and write (or scan and update to be precise) ratios when deciding whether to recommend compression and what compression type to recommend. This is parameterized:

```sql
-- 1180: The maximum ratio of updates to all operations to define "infrequent updates"
@CompressionPartitionUpdateRatioThreshold1 decimal(3,2) = 0.2,

-- 1180: The maximum ratio of updates to all operations to define "more frequent but not frequent enough updates"
@CompressionPartitionUpdateRatioThreshold2 decimal(3,2) = 0.5,

-- 1180: The minimum ratio of scans to all operations to define "frequent enough scans"
@CompressionPartitionScanRatioThreshold1 decimal(3,2) = 0.5,
```

Now, the default ratios are somewhat of a best guess, so open to adjusting that. If the results you are getting with default ratio are questionable, it would be interesting to see which adjustments make them more reasonable in your case.

We are using `sys.dm_db_index_operational_stats()` rather than `sys.dm_db_index_usage_stats`, in essence following the approach in [Data Compression: Strategy, Capacity Planning and Best Practices](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008/dd894051(v=sql.100)).

Regarding your first suggestion, I updated the wiki for [1080](https://github.com/microsoft/azure-sql-tips/wiki/Azure-SQL-Database-tips#tip_id-1180) to clarify decision points around what to compress when.

**Comment by m60freeman** [comment]
@dimitri-furman You are, of course, correct. In fact, you consider not just seeks but "user_seeks + user_scans + user_lookups".
Kalen uses at least 500 pages and 75% reads as a filter when creating the set of indexes to analyze, but does not consider cases where an index is "more frequently updated but also more frequently scanned". (The logic in that CASE statement in your code could be explained a bit in the Wiki, but is not, although the code is well commented.) 

I see your point about analyzing the small tables, although one can also make the case that if it is a small table that will be growing significantly, it is hard to guess at what the read/write ratio will look like later. In the early stages, I would presume that such a table would mostly be written to and so it would get skipped anyway. For tables that start small and stay small, such as a lookup table of a few dozen rows, those will likely stay as almost entirely read-only, making compression a tiny win. In the end, I agree with you that filtering on size is not particularly useful. 

You are effectively using the equivalent of filtering on 80% reads (@CompressionPartitionUpdateRatioThreshold1 decimal(3,2) = 0.2) and that is a small difference. Hopefully admins will run this script periodically, as databases change over time and the recommendations may as well.

In the Wiki, you state: "For most workloads, ROW compression should be enabled by default for new tables and indexes." It is probably the correct that Microsoft hasn't made that the default because it cannot be predicted in advance whether any given index or table in a general purpose database will end up having a workload skewed more toward reads or writes. 

I was recently reading https://eitanblumin.com/2022/01/17/detect-low-compression-rates-in-all-databases/ and I think you are already handling those cases. Is that true?

Adding the command needed to implement the suggestion to the Details output would be a nice enhancement. If you really wanted to go crazy, that Details output could be written as full XML so it would be easy to pop into Excel. Both of these suggestions apply to 1530 (Disabled or not trusted constraints found) and probably other sections as well.

Thanks for publishing (and maintaining) this script. This kind of analysis that creates actionable information is very helpful.

**Comment by m60freeman** [comment]
@dimitri-furman It looks good to me. A user could always do a quick find/replace on the output to change the options (ONLINE, etc.) if desired. I am not a good test case for this, as my only partitioned indexes are very write-heavy. (We use partitioning as a way to reduce blocking on the very frequent INSERTs.) But the output looks good on the databases I've run it on. I just never see anything other than "partition range: 1-1" and your code is smart enough not put a PARTITION option into the commands.

**Comment by dimitri-furman** [comment]
Thanks @m60freeman. I'll close this now, please open new issues if you have more feedback on the script.
